---

- name: Install Zookeeper
  apt: name=zookeeper update_cache=yes

- name: Install zookeeperd
  apt: name=zookeeperd

- template: src=myid dest=/etc/zookeeper/conf/myid
  notify:
    - Restart zookeeper

- template: src=zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg
  notify:
    - Restart zookeeper

- template: src=myid dest=/var/lib/zookeeper/myid
  notify:
    - Restart zookeeper

- meta: flush_handlers

- name: Install zkdump
  apt: name=zkdump state=present
