---

- name: Install EPEL repo
  yum:
    name: 'epel-release'
    state: present

- name: Install Zookeeper
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'nmap-ncat'
    - 'zookeeper'

- name: Install zkdump
  yum:
    name: 'zkdump'
    state: present
  when: zookeeper_install_zkdump|default(False)
