---

- name: Install zookeeperd
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - 'netcat-openbsd'
    - 'zookeeperd'

- name: Install zkdump
  apt:
    name: 'zkdump'
    state: present
  when: zookeeper_install_zkdump|default(False)
