---

- file: path=/usr/java state=directory

- file: src=/etc/alternatives/jre_openjdk dest=/usr/java/default state=link

- template: src=myid dest=/var/lib/zookeeper/myid

- template: src=zoo.cfg dest=/etc/zookeeper/zoo.cfg
  notify:
    - Restart zookeeper
