---

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Install Zookeeper (RedHat7)
  yum: name={{ item }} state=present
  with_items:
    - java-1.7.0-openjdk-headless
    - zookeeper
    - nmap-ncat
    - zkdump

- name: Force systemd daemon reload
  command: systemctl daemon-reload

- file: path=/usr/java state=directory

- file: src=/etc/alternatives/jre_openjdk dest=/usr/java/default state=link

- template: src=myid dest=/var/lib/zookeeper/myid

- template: src=zoo.cfg dest=/etc/zookeeper/zoo.cfg
  notify:
    - Restart zookeeper
